# Site settings
title: My Home
description: O O
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "www.zhangwangliã€‚cn" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauricio Urraco
user_description: I'm a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT.. I'm one of the two guys behind all the JS related stuff. Visit my blog here":" <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: Software Engineer
email: zhangdeyu1sdooo@163.com
# twitter_username: 
# github_username:  zhangdeyu1sdo
# gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
